// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mark_feed_fetched.sql

package database

import (
	"context"
	"database/sql"
)

const markFeed = `-- name: MarkFeed :exec
UPDATE feeds
SET last_fetched_at = $1
WHERE id = $2
`

type MarkFeedParams struct {
	LastFetchedAt sql.NullTime
	ID            int32
}

func (q *Queries) MarkFeed(ctx context.Context, arg MarkFeedParams) error {
	_, err := q.db.ExecContext(ctx, markFeed, arg.LastFetchedAt, arg.ID)
	return err
}
